app = "targettalk"
primary_region = "lax"
build = { }

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 8000
min_machines_running = 0

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "1gb"

[mounts]
source = "targettalk_data"
destination = "/data"

[env]
  PROJECT_NAME = "TargetTalkBackend"
